"""Genesis2-specific SystemVerilog parser.

This module provides :class:`Genesis2Parser`, a subclass of
:class:`svlang.parser.SVParser`, that adds support for quirks
introduced by the Genesis2 RTL generator from Stanford.  Genesis2
produces SystemVerilog modules whose headers often include
``import`` statements between the module name and the port list and
whose port declarations may include a ``var`` keyword before the
data type.  The base :class:`SVParser` only recognises ANSI style
headers and therefore fails to detect these Genesis2 modules.  This
subclass extends the module extraction logic to skip over ``import``
statements and relies on the enhanced data type parsing in the base
class to handle ``var`` and packed ranges without whitespace.

Example usage::

    from svlang.genesis2 import Genesis2Parser, MarkdownTableRenderer

    parser = Genesis2Parser()
    modules = parser.parse_file("ppc_d2d.sv")
    for m in modules:
        print(m.name)

The resulting :class:`svlang.model.Module` instances will include
their ports and parameters as usual.  No special handling is
required for the port declarations—the base parser’s port and
parameter parsing methods are reused.
"""

from __future__ import annotations

import re
from typing import List

from .parser import SVParser
from .model import Module


class Genesis2Parser(SVParser):
    """Parser for SystemVerilog modules generated by Genesis2.

    Genesis2 inserts one or more ``import <pkg>::*;`` statements
    between the ``module`` declaration and the opening parenthesis of
    the ANSI port list.  The base :class:`SVParser` treats any
    non-whitespace characters between the module name and the ``(``
    as the start of a non-ANSI module header and will skip it.  This
    subclass overrides the module extraction logic to skip over
    import statements so that the subsequent parameter and port lists
    are still parsed.
    """

    def _extract_modules(self, text: str) -> List[Module]:
        modules: List[Module] = []
        pattern = re.compile(r'\bmodule\b', re.IGNORECASE)
        idx = 0
        while True:
            m = pattern.search(text, idx)
            if not m:
                break
            start = m.start()
            # Extract module name
            name_match = re.match(r'module\s+(\w+)', text[start:], re.IGNORECASE)
            if not name_match:
                idx = m.end()
                continue
            name = name_match.group(1)
            pos = start + name_match.end()
            # Skip whitespace
            while pos < len(text) and text[pos].isspace():
                pos += 1
            # Genesis2: skip over import statements (e.g. import pkg::*;)
            while True:
                # Skip any leading whitespace
                while pos < len(text) and text[pos].isspace():
                    pos += 1
                # Check for 'import ...;' starting at this position
                imp_match = re.match(r'import\s+[^;]*;', text[pos:], re.IGNORECASE)
                if imp_match:
                    # Advance past the entire import statement
                    pos += imp_match.end()
                    continue
                break
            # Parse parameter list if present
            param_list_text = ''
            if pos < len(text) and text[pos] == '#':
                pos += 1
                # Skip whitespace
                while pos < len(text) and text[pos].isspace():
                    pos += 1
                if pos < len(text) and text[pos] == '(':  # begin parameter block
                    param_list_text, pos = self._extract_parenthesised(text, pos)
            # Skip whitespace before port list
            while pos < len(text) and text[pos].isspace():
                pos += 1
            # Parse port list
            port_list_text = ''
            if pos < len(text) and text[pos] == '(':  # begin port list
                port_list_text, pos = self._extract_parenthesised(text, pos)
            # Create module object
            parameters = self._parse_parameter_list(param_list_text)
            ports = self._parse_port_list(port_list_text)
            modules.append(Module(name=name, parameters=parameters, ports=ports))
            # Advance search index
            idx = pos
        return modules