import argparse
import sys

from svlang.strategy import LRM2017Strategy, Genesis2Strategy
from svlang.renderer import MarkdownTableRenderer, CsvTableRenderer


def cmd_fetch_if(args: argparse.Namespace) -> int:
    """Fetch interface (ports + params) and print in specified format.

    The parser strategy can be selected via the ``--strategy`` option
    on the ``fetchif`` command.  Supported strategies are ``lrm``
    (default) for IEEE LRM 2017 compliant SystemVerilog and
    ``genesis2`` for RTL generated by the Genesis2 engine.

    The output format can be selected via the ``--format`` option.
    Supported formats are ``markdown`` (default) and ``csv``.
    """
    # Select parser strategy
    if getattr(args, "strategy", "lrm") == "genesis2":
        strategy = Genesis2Strategy()
    else:
        strategy = LRM2017Strategy()

    strategy.load_design([args.file])
    modules = strategy.get_modules()

    # Select renderer based on format
    output_format = getattr(args, "format", "markdown")
    if output_format == "csv":
        renderer = CsvTableRenderer()
    else:
        renderer = MarkdownTableRenderer()

    for mod in modules:
        print(f"# Module {mod.name}\n")

        # Signal interface
        print(renderer.render_signal_table(mod.ports))
        print()

        # Parameters / generics
        print(renderer.render_parameter_table(mod.parameters))
        print()

    return 0


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="chef.py",
        description="Facade for SystemVerilog utilities.",
    )

    # Global options
    parser.add_argument(
        "--format",
        choices=["markdown", "csv"],
        default="markdown",
        help="Output format (default: markdown).",
    )

    subparsers = parser.add_subparsers(dest="command")

    # fetchif subcommand
    fetch_if = subparsers.add_parser(
        "fetchif",
        help="Fetch interface description (ports and parameters).",
    )
    fetch_if.add_argument(
        "file",
        metavar="FILE",
        help="SystemVerilog file to parse.",
    )
    fetch_if.add_argument(
        "--strategy",
        choices=["lrm", "genesis2"],
        default="genesis2",
        help=(
            "Parser strategy to use: 'lrm' for IEEE LRM 2017 SystemVerilog, "
            "'genesis2' for Genesis2-generated RTL (default: genesis2)"
        ),
    )
    fetch_if.set_defaults(func=cmd_fetch_if)

    return parser


def main(argv=None) -> int:
    if argv is None:
        argv = sys.argv[1:]

    parser = build_arg_parser()
    args = parser.parse_args(argv)

    if not hasattr(args, "func"):
        parser.print_help()
        return 1

    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
