#!/usr/bin/env bash

# Show coverage report from coverage.xml generated by test.sh --coverage
# Example usage:
# ./test.sh sanity --coverage && ./coverage.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGE_NAME=yehudats/chef:latest

docker run --rm \
  --entrypoint coverage \
  -v "$SCRIPT_DIR":/app \
  -w /app \
  "$IMAGE_NAME" \
  report --show-missing
